# Generated by Django 3.1.4 on 2022-04-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220418_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
